# Generated by Django 5.1.7 on 2025-03-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_userdb_options_alter_userdb_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdb',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='userdb',
            name='unique_active_email',
        ),
        migrations.RemoveConstraint(
            model_name='userdb',
            name='unique_active_mobile',
        ),
    ]
