# Generated by Django 5.1.7 on 2025-03-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_alter_userdb_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'verbose_name': 'Resort', 'verbose_name_plural': 'Resorts'},
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='resort',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-in Time'),
        ),
        migrations.AddField(
            model_name='resort',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Check-out Time'),
        ),
        migrations.AddField(
            model_name='resort',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Starting Price'),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_description',
            field=models.TextField(blank=True, null=True, verbose_name='Resort Description'),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Resort Email'),
        ),
        migrations.AddField(
            model_name='resort',
            name='resort_website',
            field=models.URLField(blank=True, null=True, verbose_name='Resort Website'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Account Status'),
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
