# Generated by Django 5.1.7 on 2025-03-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_resort_options_remove_userdb_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_type',
            field=models.CharField(choices=[('beach', 'Beach Resort & Spa'), ('mountain', 'Mountain & Hill Resort'), ('lake', 'Lake & Waterfront Resort'), ('forest', 'Forest & Wildlife Resort'), ('island', 'Island & Private Resort'), ('desert', 'Desert & Oasis Resort'), ('golf', 'Golf & Country Resort'), ('wellness', 'Wellness & Ayurveda Resort'), ('heritage', 'Heritage & Palace Resort'), ('eco', 'Eco & Nature Resort'), ('adventure', 'Adventure & Sports Resort'), ('boutique', 'Boutique & Luxury Resort'), ('family', 'Family & Entertainment Resort'), ('romantic', 'Romantic & Honeymoon Resort'), ('business', 'Business & Conference Resort')], max_length=50, verbose_name='Resort Type'),
        ),
    ]
