# Generated by Django 5.1.7 on 2025-03-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_alter_resort_resort_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resort',
            options={'ordering': ['resort_name'], 'verbose_name': 'Resort', 'verbose_name_plural': 'Resorts'},
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_type',
            field=models.CharField(choices=[('beach_resort', 'Beach Resort'), ('mountain_resort', 'Mountain Resort'), ('lake_resort', 'Lake Resort'), ('forest_resort', 'Forest Resort'), ('desert_resort', 'Desert Resort'), ('island_resort', 'Island Resort'), ('wellness_resort', 'Wellness Resort'), ('golf_resort', 'Golf Resort'), ('ski_resort', 'Ski Resort'), ('eco_resort', 'Eco Resort'), ('luxury_resort', 'Luxury Resort'), ('family_resort', 'Family Resort'), ('boutique_resort', 'Boutique Resort'), ('all_inclusive', 'All-Inclusive Resort'), ('casino_resort', 'Casino Resort'), ('theme_park_resort', 'Theme Park Resort'), ('villa_resort', 'Villa Resort'), ('business_resort', 'Business Resort'), ('adventure_resort', 'Adventure Resort'), ('heritage_resort', 'Heritage Resort')], max_length=50, verbose_name='Resort Type'),
        ),
        migrations.CreateModel(
            name='BookingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_patterns', models.JSONField(default=dict)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_stay_duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('repeat_customer_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('popular_add_ons', models.JSONField(default=list)),
                ('seasonal_demand', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_analytics', to='projectapp.resort')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=1.2, max_digits=4)),
                ('peak_season_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('last_minute_discount', models.DecimalField(decimal_places=2, default=0.8, max_digits=4)),
                ('advance_booking_discount', models.DecimalField(decimal_places=2, default=0.9, max_digits=4)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_history', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='projectapp.resort')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in hours for daycation or days for staycation')),
                ('package_type', models.CharField(choices=[('Staycation', 'Staycation'), ('Daycation', 'Daycation')], max_length=20)),
                ('amenities', models.TextField(help_text='Comma-separated amenities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('availability', models.PositiveIntegerField(default=10, help_text='Number of packages available')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5)),
                ('featured', models.BooleanField(default=False)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='projectapp.resort')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResortAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('peak_season_months', models.JSONField(default=list)),
                ('popular_room_types', models.JSONField(default=dict)),
                ('guest_demographics', models.JSONField(default=dict)),
                ('revenue_by_channel', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='projectapp.resort')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_revenue', models.JSONField(default=dict)),
                ('monthly_revenue', models.JSONField(default=dict)),
                ('revenue_by_room_type', models.JSONField(default=dict)),
                ('revenue_by_package', models.JSONField(default=dict)),
                ('average_daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revpar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goppar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_analytics', to='projectapp.resort')),
            ],
        ),
    ]
