# Generated by Django 5.1.7 on 2025-03-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_alter_resort_options_alter_resort_resort_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('villa', 'Villa')], max_length=10)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('cleaning', 'Being Cleaned')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.TextField(help_text='List of amenities, separated by commas')),
                ('description', models.TextField(blank=True, null=True)),
                ('size_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('view_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bed_type', models.CharField(blank=True, max_length=50, null=True)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projectapp.resort')),
            ],
            options={
                'ordering': ['room_number'],
                'unique_together': {('resort', 'room_number')},
            },
        ),
    ]
