# Generated by Django 5.1.7 on 2025-03-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='resort',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Resort'),
        ),
        migrations.AddField(
            model_name='resort',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='resort_galleries', to='projectapp.resortimage'),
        ),
        migrations.AddField(
            model_name='resort',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resort_main_image', to='projectapp.resortimage'),
        ),
        migrations.AddField(
            model_name='resort',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Reviews'),
        ),
    ]
