# Generated by Django 5.1.7 on 2025-03-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_packagebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('interests', models.JSONField(help_text='List of selected interests')),
                ('budget_range', models.CharField(choices=[('2000-5000', '₹2,000 - ₹5,000'), ('5000-10000', '₹5,000 - ₹10,000'), ('10000-20000', '₹10,000 - ₹20,000'), ('20000+', 'Above ₹20,000')], max_length=20)),
                ('preferred_duration', models.CharField(choices=[('day', 'Day Trip (4-8 hours)'), ('weekend', 'Weekend (1-2 days)'), ('week', 'Week Long (3-7 days)'), ('flexible', 'Flexible')], max_length=20)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.JSONField(blank=True, help_text='Stored package recommendations', null=True)),
            ],
            options={
                'verbose_name': 'User Interest Enquiry',
                'verbose_name_plural': 'User Interest Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
