# Generated by Django 5.1.7 on 2025-03-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_userinterestenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_category', models.CharField(choices=[('Relaxation & Wellness', 'Relaxation & Wellness'), ('Outdoor Adventure', 'Outdoor Adventure'), ('Luxury & Pampering', 'Luxury & Pampering'), ('Cultural Exploration', 'Cultural Exploration'), ('Eco-Friendly Travel', 'Eco-Friendly Travel')], max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_duration', models.CharField(choices=[('day', 'Day Trip (4-8 hours)'), ('weekend', 'Weekend (1-2 days)'), ('week', 'Week Long (3-7 days)'), ('flexible', 'Flexible')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projectapp.package')),
            ],
            options={
                'verbose_name': 'Package Recommendation',
                'verbose_name_plural': 'Package Recommendations',
                'ordering': ['-confidence_score'],
            },
        ),
    ]
