# Generated by Django 5.1.7 on 2025-03-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_packagerecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='interest_categories',
            field=models.JSONField(default=list, help_text='List of interest categories this package belongs to'),
        ),
        migrations.AddField(
            model_name='package',
            name='last_recommended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='recommendation_confidence',
            field=models.DecimalField(decimal_places=2, default=0.85, max_digits=3),
        ),
        migrations.AddField(
            model_name='package',
            name='total_recommendations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', 'average_rating'], name='projectapp__is_acti_8888f7_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['package_type', 'is_active'], name='projectapp__package_5e5d24_idx'),
        ),
    ]
